matrix:
  include:
    - language: elixir
      dist: focal

      elixir: '1.11.2'
      otp_release: '23.2'

      services:
        - postgresql

      before_install:
        - sudo apt-get install ldap-utils slapd
        - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain stable -y
        - (source $HOME/.cargo/env; cd support/tmptmpfs; cargo build)
        - (source $HOME/.cargo/env; cd support/tmptmpfs; sudo ./install.sh)

      before_script:
        - psql -U postgres -c "create user inkfish with password 'oobeiGait3ie' createdb"
        - bash test/scripts/setup.sh
    - language: node_js
      dist: focal
      nodejs: 'stable'

      before_install:
        - cd assets

      install:
        - npm install

      script:
        - npm test
