use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :inkfish, InkfishWeb.Endpoint,
  url: [host: "inkfish.ntuck-neu.site", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json"

config :inkfish, download_host: "https://inkfish.ntuck-neu.site"
config :inkfish, :env, :prod

# Do not print debug messages in production
config :logger, level: :info

config :paddle, Paddle,
  host: "ldap.ccs.neu.edu",
  base: "dc=ccs,dc=neu,dc=edu",
  account_subdn: "ou=people",
  ssl: true,
  port: 636,
  timeout: 5000,
  sslopts: [
    versions: [:'tlsv1.1'],
    ciphers: :ssl.cipher_suites(:all, :'tlsv1.2'),
  ]

# Finally import the config/prod.secret.exs which loads secrets
# and configuration from environment variables.
import_config "prod.secret.exs"
